### PR TITLE
[config] switch from libpng15 to libpng16

### PR DESCRIPTION
**Pull request by d0b3rm4n**
with next release libpng15 becomes deprecated, we should not allow it any more for new submissions to harbour.

### CODE REVIEW

**Comment by JussiPakkanen** [comment]
The commit message should say to libpng16 instead of libpng15.

**Comment by JussiPakkanen** [comment]
lgtm

**Comment by thp** [comment]
But we do still ship libpng15 as part of the device image, right? Otherwise all existing apps in harbour using the old library will break.

**Comment by d0b3rm4n** [comment]
we have libpng15-compat in the repos available, I don't think it's part by default in the image, but if something needs libpng15.so.15(PNG15_0) libpng15-compat should provide it.

**Comment by tigeli** [comment]
@thp Yes, and will do as long as libpng15 is supported by upstream and no huge security issues are left unfixed.

Otherwise, LGTM.

**Comment by thp** [comment]
Ok. Do we have a way (maybe a separate file) that we can move "deprecated but we need to support it for now" entries? Otherwise how will we know in the future which libraries we have at some point supported? Maybe we can have it in such a way that the deprecated libraries are shown as "not supported for new uploads, use <replacement> instead" warnings?

**Comment by thp** [comment]
In other words, can we create a separate file with deprecated libs to keep track of what we have allowed and have a deprecation / replacement policy in place, as we'll probably run into these things in the future?

**Comment by d0b3rm4n** [comment]
I updated the PR to contain also deprecated_libraries.conf and deprecated_requires.conf so we can track when we something deprecate. But for the moment I don't have time to also make something useful with the content of these files with the rpmvalidation.sh script it self.

**Comment by thp** [comment]
Thanks, that works for me :) LGTM

**Pull request merged**
