### PR TITLE
Allow libexpat.so.1 please

### PR DESCRIPTION
**Pull request by monich**
Very stable API. And I'll probably need it fairly soon for one of my apps.

### CODE REVIEW

**Comment by thp** [comment]
ABI compatibility report: http://upstream-tracker.org/versions/libexpat.html

**Comment by thp** [comment]
LGTM, but do we have a JB# reference for this? Also like to hear @d0b3rm4n's opinion. Also, we already allow `libxml2.so.2` -- might that work as a replacement for expat?

**Comment by d0b3rm4n** [comment]
No JB# yet, but I guess we can handle that also here.

Normally I'd say we should not allow too many libraries, providing the same functionalities.

Expat is part of default Jolla Phone image, due to:
the-vault -> git-minimal -> expat

as is libxml2:
voicecall-ui-jolla -> provisioning-service -> libxml2

so it doesn't look like that any of the 2 would disappear soon. I don't expect upstream projects to easily change to one or the other xml library.

So in that case we could make an exception. @iamer and @bwachter any objections?

Anyway the request should also include an update for allowed_requires.conf!

**Comment by d0b3rm4n** [comment]
might also be worth to check if we really need expat :) and compile git without support for DAV? To consolidate.

https://github.com/git/git/blob/master/INSTALL#L127

But that's rather a Mer discussion.

**Comment by monich** [comment]
My use case was about porting a bunch of existing code that uses libexpat, not writing one from scratch. An alternative would be to compile libexpat into the app which is also doable but hopefully can be avoided.

I'll update allowed_requires.conf as well.

**Comment by monich** [comment]
Updated allowed_requires.conf

**Comment by thp** [comment]
Looking at the version history of expat, it's probably not going to change a lot in the future, too.

The size of `/usr/lib/libexpat.so.1.6.0` on the phone is 93408 bytes, so one could argue that static linking shouldn't hurt too much, but one could also argue that it's not too big, so we should just allow it.

I'm for allowing it, it's small, stable, doesn't change a lot, and would help porting apps in slava's case :)

**Comment by JussiPakkanen** [comment]
Expat is often used to parse untrusted input, we really want people to use the system version so they all get autoupdated if vulnerabilities are found.

**Comment by iamer** [comment]
I vote for allowing it. It's obviously never going away as a lot of packages in the platform require or buildrequire it, and is very small and api stable.

**Comment by monich** [comment]
harbour.jolla.com still doesn't allow dependency on expat...

**Comment by d0b3rm4n** [comment]
yes new APIs get allowed with releases, so it will be allowed with 1.1.8/9 (what ever number the release after 1.1.7 will have)

**Pull request merged**
