### PR TITLE
[conf] Allow the Sailfish Pickers API. Contributes to JB#19575

### PR DESCRIPTION
**Pull request by jlehtoranta**

### CODE REVIEW

**Comment by kimmoli** [comment]
Out of curiosity, what is the usecase for this API?
I have used these for ages by pushing them in pagestack

     var imagePicker = pageStack.push("Sailfish.Pickers.ImagePickerPage", { "allowedOrientations" : Orientation.All });

**Comment by jpetrell** [comment]
LGTM

**Comment by jpetrell** [comment]
Sailfish Pickers haven't been officially supported API. Now we finally had time to clean up the implementation and wrote API documentation. You risk breaking your app if you hack your way around. 

That being said we should have published this ages ago.

**Comment by kimmoli** [comment]
Ok. thanks.
Can we have pointers to the API documentation?

**Comment by martyone** [comment]
@kimmoli _When released_ you will find the docs in Sailfish OS SDK and also here https://sailfishos.org/wiki/Application_Development#API_Documentation.

**Comment by kimmoli** [comment]
👍

**Pull request merged**
